
const planes: { [id: string]: string } = {
  'AT75': 'ATR 72-500',
  'A20N': 'Airbus A320neo',
  'A21N': 'Airbus A321neo',
  'A319': 'Airbus A319',
  'A320': 'Airbus A320',
  'A321': 'Airbus A321',
  'A332': 'Airbus A330-200',
  'A333': 'Airbus A330-300',
  'A338': 'Airbus A330-800neo',
  'A339': 'Airbus A330-900neo',
  'B38M': 'Boeing 737 MAX 8',
  'B734': 'Boeing 737-400',
  'B738': 'Boeing 737-800',
  'B752': 'Boeing 757-200',
  'B762': 'Boeing 767-200',
  'B763': 'Boeing 767-300',
  'B772': 'Boeing 777-200',
  'B77W': 'Boeing 777-300ER',
  'B788': 'Boeing 787-8',
  'B789': 'Boeing 787-9',
  'B78X': 'Boeing 787-10',
  'BCS3': 'Bombardier CS300',
  'CRJ2': 'Mitsubishi CRJ-200ER',
  'CRJX': 'Mitsubishi CRJ-1000',
  'E190': 'Embraer E190',
  'E195': 'Embraer E195',
  'GLEX': 'Bombardier Global Express',
  'GL5T': 'Bombardier Global 5000',
  'GL6T': 'Bombardier Global 6000',
  'G650': 'Gulfstream G650',
  'G550': 'Gulfstream G550',
  'G500': 'Gulfstream G500',
  'GALX': 'Gulfstream Galaxy',
  'F900': 'Dassault Falcon 900',
  'F7X':  'Dassault Falcon 7X',
  'F2TH': 'Dassault Falcon 2000',
  'C56X': 'Cessna Citation Excel',
  'C680': 'Cessna Citation Sovereign',
  'C750': 'Cessna Citation X',
  'CL30': 'Bombardier Challenger 300',
  'CL35': 'Bombardier Challenger 350',
  'CL60': 'Bombardier Challenger 600',
  'E55P': 'Embraer Phenom 300',
  'PC12': 'Pilatus PC-12',
}

export const getPlane = (type: string) => planes[type] || type;

const airlines: { [id: string]: string } = {
  '3P': 'World2Fly',
  '3V': 'ASL Airlines Belgium',
  '5F': 'Fly One',
  '6H': 'Israir',
  '6O': 'Orbest',
  'A3': 'Aegean Airlines',
  'AA': 'American Airlines',
  'AC': 'Air Canada',
  'AF': 'Air France',
  'AH': 'Air Algérie',
  'AT': 'Royal Air Maroc',
  'AY': 'Finnair',
  'BA': 'British Airways',
  'BT': 'Air Baltic',
  'BJ': 'Nouvelair',
  'DL': 'Delta Air Lines',
  'DS': 'EasyJet Switzerland',
  'DT': 'TAAG Angola Airlines',
  'DY': 'Norwegian Air Shuttle',
  'EI': 'Aer Lingus',
  'EW': 'Eurowings',
  'FR': 'Ryanair',
  'HT': 'Air Horizont',
  'HV': 'Transavia',
  'IB': 'Iberia',
  'KL': 'KLM',
  'LH': 'Lufthansa',
  'LG': 'Luxair',
  'LO': 'LOT Polish Airlines',
  'LX': 'Swiss International Air Lines',
  'LY': 'El Al',
  'MS': 'EgyptAir',
  'OB': 'Orbest',
  'OG': 'PLAY',
  'OU': 'Croatia Airlines',
  'PC': 'Pegasus Airlines',
  'QR': 'Qatar Airways',
  'QY': 'European Air Transport Leipzig',
  'RK': 'Ryanair UK',
  'S4': 'SATA Air Açores',
  'SN': 'Brussels Airlines',
  'TK': 'Turkish Airlines',
  'TM': 'LAM Mozambique Airlines',
  'TO': 'Transavia France',
  'TP': 'TAP Portugal',
  'TS': 'Air Transat',
  'TU': 'Tunisair',
  'U2': 'easyJet Europe',
  'UA': 'United Airlines',
  'UX': 'Air Europa',
  'VR': 'Cabo Verde Airlines',
  'VY': 'Vueling',
  'WT': 'Swiftair',
  'W6': 'Wizz Air',
  'W9': 'Wizz Air UK',
  'YU': 'EuroAtlantic Airways',
  'YW': 'Air Nostrum Iberia Regional',
  'ZB': 'Air Albania',
}

// Accepts either a 2-char IATA airline code ("BA") or a full flight number ("BA123").
// Extracts the first 2 characters either way.
export const getAirline = (codeOrFlight: string) => codeOrFlight ? airlines[codeOrFlight.substring(0, 2)] || codeOrFlight.substring(0, 2) : '?';

export interface Airport {
  name: string;
  flag: string;
  useCode?: boolean;
}

const airports: { [id: string]: Airport } = {
  'ACE': { name: 'Lanzarote', flag: '🇪🇸' },
  'AGA': { name: 'Agadir', flag: '🇲🇦' },
  'AGP': { name: 'Málaga', flag: '🇪🇸' },
  'ALA': { name: 'Almaty', flag: '🇰🇿' },
  'ALC': { name: 'Alicante', flag: '🇪🇸' },
  'AMM': { name: 'Amman', flag: '🇯🇴' },
  'AUH': { name: 'Abu Dhabi', flag: '🇦🇪' },
  'ALG': { name: 'Algiers', flag: '🇩🇿' },
  'AMS': { name: 'Amsterdam', flag: '🇳🇱' },
  'ARN': { name: 'Stockholm', flag: '🇸🇪' },
  'ATH': { name: 'Athens', flag: '🇬🇷' },
  'ATL': { name: 'Atlanta', flag: '🇺🇸' },
  'BCN': { name: 'Barcelona', flag: '🇪🇸' },
  'BAH': { name: 'Bahrain', flag: '🇧🇭' },
  'BEG': { name: 'Belgrade', flag: '🇷🇸' },
  'BER': { name: 'Berlin', flag: '🇩🇪' },
  'BEY': { name: 'Beirut', flag: '🇱🇧' },
  'BRI': { name: 'Bari', flag: '🇮🇹' },
  'BRN': { name: 'Bern', flag: '🇨🇭' },
  'BRQ': { name: 'Brno', flag: '🇨🇿' },
  'BTS': { name: 'Bratislava', flag: '🇸🇰' },
  'BCM': { name: 'Bacău', flag: '🇷🇴' },
  'BFS': { name: 'Belfast', flag: '🇬🇧' },
  'BHD': { name: 'Belfast City', flag: '🇬🇧' },
  'BGY': { name: 'Milan Bergamo', flag: '🇮🇹' },
  'BHX': { name: 'Birmingham', flag: '🇬🇧' },
  'BIO': { name: 'Bilbao', flag: '🇪🇸' },
  'BLQ': { name: 'Bologna', flag: '🇮🇹' },
  'BOD': { name: 'Bordeaux', flag: '🇫🇷' },
  'BOM': { name: 'Mumbai', flag: '🇮🇳' },
  'BOS': { name: 'Boston', flag: '🇺🇸' },
  'BRU': { name: 'Brussels', flag: '🇧🇪' },
  'BRS': { name: 'Bristol', flag: '🇬🇧' },
  'BSL': { name: 'Basel', flag: '🇨🇭' },
  'BUD': { name: 'Budapest', flag: '🇭🇺' },
  'BVA': { name: 'Beauvais', flag: '🇫🇷' },
  'CAI': { name: 'Cairo', flag: '🇪🇬' },
  'CFU': { name: 'Corfu', flag: '🇬🇷' },
  'CLJ': { name: 'Cluj-Napoca', flag: '🇷🇴' },
  'CRA': { name: 'Craiova', flag: '🇷🇴' },
  'CHQ': { name: 'Chania', flag: '🇬🇷' },
  'CTA': { name: 'Catania', flag: '🇮🇹' },
  'CDG': { name: 'Paris Charles de Gaulle', flag: '🇫🇷' },
  'CGN': { name: 'Cologne', flag: '🇩🇪' },
  'CIA': { name: 'Rome Ciampino', flag: '🇮🇹' },
  'CLT': { name: 'Charlotte', flag: '🇺🇸' },
  'CMN': { name: 'Casablanca', flag: '🇲🇦' },
  'CPH': { name: 'Copenhagen', flag: '🇩🇰' },
  'CRL': { name: 'Brussels Charleroi', flag: '🇧🇪' },
  'CUN': { name: 'Cancún', flag: '🇲🇽' },
  'CSX': { name: 'Changsha', flag: '🇨🇳' },
  'DBV': { name: 'Dubrovnik', flag: '🇭🇷' },
  'DEL': { name: 'Delhi', flag: '🇮🇳' },
  'DJE': { name: 'Djerba', flag: '🇹🇳' },
  'DME': { name: 'Moscow Domodedovo', flag: '🇷🇺' },
  'DND': { name: 'Dundee', flag: '🇬🇧' },
  'DOH': { name: 'Doha', flag: '🇶🇦' },
  'DRS': { name: 'Dresden', flag: '🇩🇪' },
  'DSS': { name: 'Dakar', flag: '🇸🇳' },
  'DUB': { name: 'Dublin', flag: '🇮🇪' },
  'DUS': { name: 'Düsseldorf', flag: '🇩🇪' },
  'DXB': { name: 'Dubai', flag: '🇦🇪' },
  'EDI': { name: 'Edinburgh', flag: '🇬🇧' },
  'EVN': { name: 'Yerevan', flag: '🇦🇲' },
  'EIN': { name: 'Eindhoven', flag: '🇳🇱' },
  'ESB': { name: 'Ankara', flag: '🇹🇷' },
  'EWR': { name: 'Newark', flag: '🇺🇸' },
  'EZE': { name: 'Buenos Aires', flag: '🇦🇷' },
  'FAO': { name: 'Faro', flag: '🇵🇹' },
  'FCO': { name: 'Rome Fiumicino', flag: '🇮🇹' },
  'FNC': { name: 'Funchal', flag: '🇵🇹' },
  'FDH': { name: 'Friedrichshafen', flag: '🇩🇪' },
  'FRA': { name: 'Frankfurt', flag: '🇩🇪' },
  'FLR': { name: 'Florence', flag: '🇮🇹' },
  'FUE': { name: 'Fuerteventura', flag: '🇪🇸' },
  'GCI': { name: 'Guernsey', flag: '🇬🇬' },
  'GDN': { name: 'Gdańsk', flag: '🇵🇱' },
  'GYD': { name: 'Baku', flag: '🇦🇿' },
  'HAJ': { name: 'Hanover', flag: '🇩🇪' },
  'HER': { name: 'Heraklion', flag: '🇬🇷' },
  'GRU': { name: 'São Paulo', flag: '🇧🇷' },
  'GIG': { name: 'Rio de Janeiro', flag: '🇧🇷' },
  'GOT': { name: 'Gothenburg', flag: '🇸🇪' },
  'GRZ': { name: 'Graz', flag: '🇦🇹' },
  'GVA': { name: 'Geneva', flag: '🇨🇭' },
  'HAM': { name: 'Hamburg', flag: '🇩🇪' },
  'HEL': { name: 'Helsinki', flag: '🇫🇮' },
  'HKG': { name: 'Hong Kong', flag: '🇭🇰' },
  'HND': { name: 'Tokyo Haneda', flag: '🇯🇵' },
  'IAD': { name: 'Washington Dulles', flag: '🇺🇸' },
  'IAS': { name: 'Iași', flag: '🇷🇴' },
  'IBZ': { name: 'Ibiza', flag: '🇪🇸' },
  'ICN': { name: 'Seoul Incheon', flag: '🇰🇷' },
  'INN': { name: 'Innsbruck', flag: '🇦🇹' },
  'IST': { name: 'Istanbul', flag: '🇹🇷' },
  'JED': { name: 'Jeddah', flag: '🇸🇦' },
  'JFK': { name: 'New York JFK', flag: '🇺🇸' },
  'JMK': { name: 'Mykonos', flag: '🇬🇷' },
  'KBP': { name: 'Kyiv Boryspil', flag: '🇺🇦' },
  'KGS': { name: 'Kos', flag: '🇬🇷' },
  'KLU': { name: 'Klagenfurt', flag: '🇦🇹' },
  'KRK': { name: 'Krakow', flag: '🇵🇱' },
  'KSC': { name: 'Košice', flag: '🇸🇰' },
  'KTW': { name: 'Katowice', flag: '🇵🇱' },
  'KWI': { name: 'Kuwait City', flag: '🇰🇼' },
  'KEF': { name: 'Reykjavik', flag: '🇮🇸' },
  'LAD': { name: 'Luanda', flag: '🇦🇴' },
  'LAX': { name: 'Los Angeles', flag: '🇺🇸' },
  'LCA': { name: 'Larnaca', flag: '🇨🇾' },
  'LNZ': { name: 'Linz', flag: '🇦🇹' },
  'BQH': { name: 'Biggin Hill', flag: '🇬🇧', useCode: true },
  'FAB': { name: 'Farnborough', flag: '🇬🇧', useCode: true },
  'NHT': { name: 'RAF Northolt', flag: '🇬🇧', useCode: true },
  'SEN': { name: 'London Southend', flag: '🇬🇧', useCode: true },
  'ABZ': { name: 'Aberdeen', flag: '🇬🇧' },
  'BOH': { name: 'Bournemouth', flag: '🇬🇧' },
  'CWL': { name: 'Cardiff', flag: '🇬🇧' },
  'EXT': { name: 'Exeter', flag: '🇬🇧' },
  'GLA': { name: 'Glasgow', flag: '🇬🇧' },
  'HUY': { name: 'Humberside', flag: '🇬🇧' },
  'INV': { name: 'Inverness', flag: '🇬🇧' },
  'LBA': { name: 'Leeds Bradford', flag: '🇬🇧' },
  'MME': { name: 'Durham Tees Valley', flag: '🇬🇧' },
  'NCL': { name: 'Newcastle', flag: '🇬🇧' },
  'NQY': { name: 'Newquay', flag: '🇬🇧' },
  'SOU': { name: 'Southampton', flag: '🇬🇧' },
  'LED': { name: 'St Petersburg', flag: '🇷🇺' },
  'LGG': { name: 'Liège', flag: '🇧🇪' },
  'LCY': { name: 'London City', flag: '🇬🇧', useCode: true },
  'LGW': { name: 'London Gatwick', flag: '🇬🇧', useCode: true },
  'LHR': { name: 'London Heathrow', flag: '🇬🇧', useCode: true },
  'LIN': { name: 'Milan Linate', flag: '🇮🇹' },
  'LJU': { name: 'Ljubljana', flag: '🇸🇮' },
  'LIS': { name: 'Lisbon', flag: '🇵🇹' },
  'LPA': { name: 'Gran Canaria', flag: '🇪🇸' },
  'LTN': { name: 'London Luton', flag: '🇬🇧', useCode: true },
  'LUX': { name: 'Luxembourg', flag: '🇱🇺' },
  'LYS': { name: 'Lyon', flag: '🇫🇷' },
  'MAD': { name: 'Madrid', flag: '🇪🇸' },
  'MAH': { name: 'Menorca', flag: '🇪🇸' },
  'MAN': { name: 'Manchester', flag: '🇬🇧' },
  'MIA': { name: 'Miami', flag: '🇺🇸' },
  'MLA': { name: 'Malta', flag: '🇲🇹' },
  'MPM': { name: 'Maputo', flag: '🇲🇿' },
  'MCT': { name: 'Muscat', flag: '🇴🇲' },
  'MPL': { name: 'Montpellier', flag: '🇫🇷' },
  'MRS': { name: 'Marseille', flag: '🇫🇷' },
  'MST': { name: 'Maastricht', flag: '🇳🇱' },
  'MUC': { name: 'Munich', flag: '🇩🇪' },
  'MXP': { name: 'Milan Malpensa', flag: '🇮🇹' },
  'NAP': { name: 'Naples', flag: '🇮🇹' },
  'NQZ': { name: 'Astana', flag: '🇰🇿' },
  'NUE': { name: 'Nuremberg', flag: '🇩🇪' },
  'NCE': { name: 'Nice', flag: '🇫🇷' },
  'NTE': { name: 'Nantes', flag: '🇫🇷' },
  'OPO': { name: 'Porto', flag: '🇵🇹' },
  'ORD': { name: 'Chicago O\'Hare', flag: '🇺🇸' },
  'ORY': { name: 'Paris Orly', flag: '🇫🇷' },
  'OHD': { name: 'Ohrid', flag: '🇲🇰' },
  'OSL': { name: 'Oslo', flag: '🇳🇴' },
  'OTP': { name: 'Bucharest', flag: '🇷🇴' },
  'OUD': { name: 'Oujda', flag: '🇲🇦' },
  'OVD': { name: 'Asturias', flag: '🇪🇸' },
  'OXF': { name: 'Oxford', flag: '🇬🇧' },
  'PDL': { name: 'Ponta Delgada', flag: '🇵🇹' },
  'PHL': { name: 'Philadelphia', flag: '🇺🇸' },
  'PHX': { name: 'Phoenix', flag: '🇺🇸' },
  'PMI': { name: 'Palma de Mallorca', flag: '🇪🇸' },
  'PMO': { name: 'Palermo', flag: '🇮🇹' },
  'PSA': { name: 'Pisa', flag: '🇮🇹' },
  'PUY': { name: 'Pula', flag: '🇭🇷' },
  'POZ': { name: 'Poznań', flag: '🇵🇱' },
  'PDV': { name: 'Plovdiv', flag: '🇧🇬' },
  'PEK': { name: 'Beijing Capital', flag: '🇨🇳' },
  'PKX': { name: 'Beijing Daxing', flag: '🇨🇳' },
  'PRG': { name: 'Prague', flag: '🇨🇿' },
  'PUJ': { name: 'Punta Cana', flag: '🇩🇴' },
  'PVG': { name: 'Shanghai Pudong', flag: '🇨🇳' },
  'RAI': { name: 'Praia', flag: '🇨🇻' },
  'RAK': { name: 'Marrakesh', flag: '🇲🇦' },
  'REC': { name: 'Recife', flag: '🇧🇷' },
  'RHO': { name: 'Rhodes', flag: '🇬🇷' },
  'RIX': { name: 'Riga', flag: '🇱🇻' },
  'RMO': { name: 'Chișinău', flag: '🇲🇩' },
  'RUH': { name: 'Riyadh', flag: '🇸🇦' },
  'RZE': { name: 'Rzeszów', flag: '🇵🇱' },
  'SAW': { name: 'Istanbul Sabiha', flag: '🇹🇷' },
  'SKG': { name: 'Thessaloniki', flag: '🇬🇷' },
  'SKP': { name: 'Skopje', flag: '🇲🇰' },
  'SOF': { name: 'Sofia', flag: '🇧🇬' },
  'SVO': { name: 'Moscow Sheremetyevo', flag: '🇷🇺' },
  'SXB': { name: 'Strasbourg', flag: '🇫🇷' },
  'RTM': { name: 'Rotterdam', flag: '🇳🇱' },
  'SBZ': { name: 'Sibiu', flag: '🇷🇴' },
  'SCV': { name: 'Suceava', flag: '🇷🇴' },
  'SDR': { name: 'Santander', flag: '🇪🇸' },
  'SFO': { name: 'San Francisco', flag: '🇺🇸' },
  'SID': { name: 'Sal', flag: '🇨🇻' },
  'SPU': { name: 'Split', flag: '🇭🇷' },
  'STN': { name: 'London Stansted', flag: '🇬🇧', useCode: true },
  'STR': { name: 'Stuttgart', flag: '🇩🇪' },
  'SVQ': { name: 'Seville', flag: '🇪🇸' },
  'SZG': { name: 'Salzburg', flag: '🇦🇹' },
  'SZZ': { name: 'Szczecin', flag: '🇵🇱' },
  'TAS': { name: 'Tashkent', flag: '🇺🇿' },
  'TBS': { name: 'Tbilisi', flag: '🇬🇪' },
  'TER': { name: 'Terceira', flag: '🇵🇹' },
  'TFS': { name: 'Tenerife South', flag: '🇪🇸' },
  'TFN': { name: 'Tenerife North', flag: '🇪🇸' },
  'TGD': { name: 'Podgorica', flag: '🇲🇪' },
  'TGM': { name: 'Târgu Mureș', flag: '🇷🇴' },
  'TIA': { name: 'Tirana', flag: '🇦🇱' },
  'TSF': { name: 'Venice Treviso', flag: '🇮🇹' },
  'TSR': { name: 'Timișoara', flag: '🇷🇴' },
  'TIV': { name: 'Tivat', flag: '🇲🇪' },
  'TLL': { name: 'Tallinn', flag: '🇪🇪' },
  'TLV': { name: 'Tel Aviv', flag: '🇮🇱' },
  'TLS': { name: 'Toulouse', flag: '🇫🇷' },
  'TNG': { name: 'Tangier', flag: '🇲🇦' },
  'TPE': { name: 'Taipei', flag: '🇹🇼' },
  'TRF': { name: 'Oslo Torp', flag: '🇳🇴' },
  'TUN': { name: 'Tunis', flag: '🇹🇳' },
  'VCE': { name: 'Venice', flag: '🇮🇹' },
  'VIE': { name: 'Vienna', flag: '🇦🇹' },
  'VIT': { name: 'Vitoria', flag: '🇪🇸' },
  'VNO': { name: 'Vilnius', flag: '🇱🇹' },
  'VRN': { name: 'Verona', flag: '🇮🇹' },
  'VGO': { name: 'Vigo', flag: '🇪🇸' },
  'VLC': { name: 'Valencia', flag: '🇪🇸' },
  'VRA': { name: 'Varadero', flag: '🇨🇺' },
  'WAW': { name: 'Warsaw', flag: '🇵🇱' },
  'WMI': { name: 'Warsaw Modlin', flag: '🇵🇱' },
  'WRO': { name: 'Wrocław', flag: '🇵🇱' },
  'BZG': { name: 'Bydgoszcz', flag: '🇵🇱' },
  'YUL': { name: 'Montreal', flag: '🇨🇦' },
  'YYC': { name: 'Calgary', flag: '🇨🇦' },
  'YVR': { name: 'Vancouver', flag: '🇨🇦' },
  'YYZ': { name: 'Toronto', flag: '🇨🇦' },
  'ZAD': { name: 'Zadar', flag: '🇭🇷' },
  'ZAG': { name: 'Zagreb', flag: '🇭🇷' },
  'ZTH': { name: 'Zakynthos', flag: '🇬🇷' },
  'ZRH': { name: 'Zurich', flag: '🇨🇭' },
  'ZYL': { name: 'Sylhet', flag: '🇧🇩' },
};

export const isKnownAirport = (code: string): boolean => code in airports;

export const getAirport = (airport: string) => airports[airport] || { name: airport ? `Abroad (${airport})` : 'Abroad', flag: '🌍' };

export const getAirportName = (code: string) => {
  const a = getAirport(code);
  return a.useCode ? code : a.name;
};
